### PR TITLE
creating file to control repository settings

### PR DESCRIPTION
**Pull request by maciejduk**
## Description

This is required as part of the solution implemented for creating Stories in ServiceNow automatically. This is to help us track our time.

## Fixed issues

This is tracked in [ip-sre-taskboard/issues/33](https://github.com/Insight-EMEA/ip-sre-taskboard/issues/33)

- [x] Updated title of the Pull Request
- [x] **Description** above is completed
- [x] Linked all issues fixed by this PR
- [x] Checked linked issues for any potential tasks **still outstanding**
- [x] All persons involved in this change are **assigned** to this PR
- [x] Appropriate **approvers** are requested and notified
- [x] Pull request is **labelled** appropriately

### CODE REVIEW

**Comment by maciejduk** [comment]
@MatthewBieda  can you review and highlight any objections please

**Comment by maciejduk** [comment]
@MatthewBieda does this repository need to remain `Public` ?

**Comment by MatthewBieda** [comment]
@maciejduk I don't think so, i think the workflows would still work

**Comment by maciejduk** [comment]
> @maciejduk I don't think so, i think the workflows would still work

Are you going to approve it then 😂

**Comment by MatthewBieda** [comment]
I'm not sure what will happen since it says changing the visibility of forks isn't possible.

**Comment by maciejduk** [comment]
> I'm not sure what will happen since it says changing the visibility of forks isn't possible.

We're never going to find out if you don't approve this PR😜

**Pull request merged**
